version: '3.8'

services:
  app:
    container_name: gst_django
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    volumes:
      - ./app:/app
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c "
              python manage.py collectstatic
              gunicorn -c config/gunicorn/dev.py
              
              "
    env_file:
      - ./.prod.env
    restart:
      on-failure
  nginx:
    container_name: gst_nginx
    build:
      ./app/store_vue
    ports:
      - "80:80"
    restart:
      on-failure
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - app

volumes:
  static_volume:
  media_volume: