version: '3.8'

services:
  app:
    container_name: gst_django
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 manage.py runserver 0.0.0:8000"
    env_file:
      - ./.dev.env
    depends_on:
      - db

  db:
    container_name: gst_db
    image: postgres:12-alpine
    env_file:
      - ./.dev.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # frontend:
  #   build:
  #     ./app/store_vue
  #   command: >
  #     sh -c "npm run build"
  #   ports:
  #     - "8080:8080"
  nginx:
    container_name: gst_nginx
    build:
      ./app/store_vue
    ports:
      - "80:80"
    restart:
      on-failure
    depends_on:
      - app

volumes:
  pgdata: