# Generated by Django 3.2.8 on 2022-09-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_result_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='processed',
            new_name='delivered',
        ),
    ]
